
package org.donstu.async;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HhService", targetNamespace = "https://donstu.org/hh")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HhService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.donstu.async.GetCompanyListResponse>
     */
    @WebMethod(operationName = "getCompanyList")
    @RequestWrapper(localName = "getCompanyList", targetNamespace = "https://donstu.org/hh", className = "org.donstu.async.GetCompanyList")
    @ResponseWrapper(localName = "getCompanyListResponse", targetNamespace = "https://donstu.org/hh", className = "org.donstu.async.GetCompanyListResponse")
    public Response<GetCompanyListResponse> getCompanyListAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getCompanyList")
    @RequestWrapper(localName = "getCompanyList", targetNamespace = "https://donstu.org/hh", className = "org.donstu.async.GetCompanyList")
    @ResponseWrapper(localName = "getCompanyListResponse", targetNamespace = "https://donstu.org/hh", className = "org.donstu.async.GetCompanyListResponse")
    public Future<?> getCompanyListAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetCompanyListResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.async.Company>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompanyList", targetNamespace = "https://donstu.org/hh", className = "org.donstu.async.GetCompanyList")
    @ResponseWrapper(localName = "getCompanyListResponse", targetNamespace = "https://donstu.org/hh", className = "org.donstu.async.GetCompanyListResponse")
    @Action(input = "https://donstu.org/hh/HhService/getCompanyListRequest", output = "https://donstu.org/hh/HhService/getCompanyListResponse")
    public List<Company> getCompanyList();

}
