
package org.donstu.async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HhService", targetNamespace = "https://donstu.org/hh", wsdlLocation = "http://127.0.0.1:8088/hh?wsdl")
public class HhService_Service
    extends Service
{

    private final static URL HHSERVICE_WSDL_LOCATION;
    private final static WebServiceException HHSERVICE_EXCEPTION;
    private final static QName HHSERVICE_QNAME = new QName("https://donstu.org/hh", "HhService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8088/hh?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HHSERVICE_WSDL_LOCATION = url;
        HHSERVICE_EXCEPTION = e;
    }

    public HhService_Service() {
        super(__getWsdlLocation(), HHSERVICE_QNAME);
    }

    public HhService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HHSERVICE_QNAME, features);
    }

    public HhService_Service(URL wsdlLocation) {
        super(wsdlLocation, HHSERVICE_QNAME);
    }

    public HhService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HHSERVICE_QNAME, features);
    }

    public HhService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HhService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HhService
     */
    @WebEndpoint(name = "HhPort")
    public HhService getHhPort() {
        return super.getPort(new QName("https://donstu.org/hh", "HhPort"), HhService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HhService
     */
    @WebEndpoint(name = "HhPort")
    public HhService getHhPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://donstu.org/hh", "HhPort"), HhService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HHSERVICE_EXCEPTION!= null) {
            throw HHSERVICE_EXCEPTION;
        }
        return HHSERVICE_WSDL_LOCATION;
    }

}
