
package org.donstu.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HhService", targetNamespace = "https://donstu.org/hh")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HhService {


    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.client.Company>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompanyList", targetNamespace = "https://donstu.org/hh", className = "org.donstu.client.GetCompanyList")
    @ResponseWrapper(localName = "getCompanyListResponse", targetNamespace = "https://donstu.org/hh", className = "org.donstu.client.GetCompanyListResponse")
    @Action(input = "https://donstu.org/hh/HhService/getCompanyListRequest", output = "https://donstu.org/hh/HhService/getCompanyListResponse")
    public List<Company> getCompanyList();

}
